# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fromAndEncryptionModeHorizontalLayout = QtWidgets.QHBoxLayout()
        self.fromAndEncryptionModeHorizontalLayout.setObjectName("fromAndEncryptionModeHorizontalLayout")
        self.encryptionModeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.encryptionModeGroupBox.setObjectName("encryptionModeGroupBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.encryptionModeGroupBox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.encryptionModeGroupBoxHorizontalLayout = QtWidgets.QHBoxLayout()
        self.encryptionModeGroupBoxHorizontalLayout.setObjectName("encryptionModeGroupBoxHorizontalLayout")
        self.encryptionModeRadioButton = QtWidgets.QRadioButton(self.encryptionModeGroupBox)
        self.encryptionModeRadioButton.setChecked(True)
        self.encryptionModeRadioButton.setObjectName("encryptionModeRadioButton")
        self.encryptionModeGroupBoxHorizontalLayout.addWidget(self.encryptionModeRadioButton)
        self.decryptionModeRadioButton = QtWidgets.QRadioButton(self.encryptionModeGroupBox)
        self.decryptionModeRadioButton.setObjectName("decryptionModeRadioButton")
        self.encryptionModeGroupBoxHorizontalLayout.addWidget(self.decryptionModeRadioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.encryptionModeGroupBoxHorizontalLayout.addItem(spacerItem)
        self.horizontalLayout_7.addLayout(self.encryptionModeGroupBoxHorizontalLayout)
        self.fromAndEncryptionModeHorizontalLayout.addWidget(self.encryptionModeGroupBox)
        self.fromGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.fromGroupBox.setObjectName("fromGroupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.fromGroupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.fromGroupBoxHorizontalLayout = QtWidgets.QHBoxLayout()
        self.fromGroupBoxHorizontalLayout.setObjectName("fromGroupBoxHorizontalLayout")
        self.fromPlainTextRadioButton = QtWidgets.QRadioButton(self.fromGroupBox)
        self.fromPlainTextRadioButton.setChecked(True)
        self.fromPlainTextRadioButton.setObjectName("fromPlainTextRadioButton")
        self.fromGroupBoxHorizontalLayout.addWidget(self.fromPlainTextRadioButton)
        self.fromFileRadioButton = QtWidgets.QRadioButton(self.fromGroupBox)
        self.fromFileRadioButton.setObjectName("fromFileRadioButton")
        self.fromGroupBoxHorizontalLayout.addWidget(self.fromFileRadioButton)
        self.horizontalLayout_6.addLayout(self.fromGroupBoxHorizontalLayout)
        self.fromAndEncryptionModeHorizontalLayout.addWidget(self.fromGroupBox)
        self.toGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.toGroupBox.setObjectName("toGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.toGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.toGroupBoxHorizontalLayout = QtWidgets.QHBoxLayout()
        self.toGroupBoxHorizontalLayout.setObjectName("toGroupBoxHorizontalLayout")
        self.toPlainTextRadioButton = QtWidgets.QRadioButton(self.toGroupBox)
        self.toPlainTextRadioButton.setChecked(True)
        self.toPlainTextRadioButton.setObjectName("toPlainTextRadioButton")
        self.toGroupBoxHorizontalLayout.addWidget(self.toPlainTextRadioButton)
        self.toFileRadioButton = QtWidgets.QRadioButton(self.toGroupBox)
        self.toFileRadioButton.setObjectName("toFileRadioButton")
        self.toGroupBoxHorizontalLayout.addWidget(self.toFileRadioButton)
        self.gridLayout.addLayout(self.toGroupBoxHorizontalLayout, 0, 0, 1, 1)
        self.fromAndEncryptionModeHorizontalLayout.addWidget(self.toGroupBox)
        self.verticalLayout.addLayout(self.fromAndEncryptionModeHorizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.encryptionMethodLabel = QtWidgets.QLabel(self.centralwidget)
        self.encryptionMethodLabel.setObjectName("encryptionMethodLabel")
        self.horizontalLayout_4.addWidget(self.encryptionMethodLabel)
        self.encryptionMethodComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.encryptionMethodComboBox.setObjectName("encryptionMethodComboBox")
        self.horizontalLayout_4.addWidget(self.encryptionMethodComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pathToSourceGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.pathToSourceGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.pathToSourceGroupBox.setObjectName("pathToSourceGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pathToSourceGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pathToSourceLineEdit = QtWidgets.QLineEdit(self.pathToSourceGroupBox)
        self.pathToSourceLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.pathToSourceLineEdit.setObjectName("pathToSourceLineEdit")
        self.horizontalLayout.addWidget(self.pathToSourceLineEdit)
        self.viewSourcePushButton = QtWidgets.QPushButton(self.pathToSourceGroupBox)
        self.viewSourcePushButton.setEnabled(True)
        self.viewSourcePushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.viewSourcePushButton.setObjectName("viewSourcePushButton")
        self.horizontalLayout.addWidget(self.viewSourcePushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.pathToSourceGroupBox)
        self.pathToDestFileGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.pathToDestFileGroupBox.setObjectName("pathToDestFileGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pathToDestFileGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pathToDestLineEdit = QtWidgets.QLineEdit(self.pathToDestFileGroupBox)
        self.pathToDestLineEdit.setObjectName("pathToDestLineEdit")
        self.horizontalLayout_3.addWidget(self.pathToDestLineEdit)
        self.viewDestPushButton = QtWidgets.QPushButton(self.pathToDestFileGroupBox)
        self.viewDestPushButton.setObjectName("viewDestPushButton")
        self.horizontalLayout_3.addWidget(self.viewDestPushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.pathToDestFileGroupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sourceVerticalLayout = QtWidgets.QVBoxLayout()
        self.sourceVerticalLayout.setObjectName("sourceVerticalLayout")
        self.sourceLabel = QtWidgets.QLabel(self.centralwidget)
        self.sourceLabel.setObjectName("sourceLabel")
        self.sourceVerticalLayout.addWidget(self.sourceLabel)
        self.sourcePlainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.sourcePlainTextEdit.setObjectName("sourcePlainTextEdit")
        self.sourceVerticalLayout.addWidget(self.sourcePlainTextEdit)
        self.horizontalLayout_2.addLayout(self.sourceVerticalLayout)
        self.resultVerticalLayout = QtWidgets.QVBoxLayout()
        self.resultVerticalLayout.setObjectName("resultVerticalLayout")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setObjectName("resultLabel")
        self.resultVerticalLayout.addWidget(self.resultLabel)
        self.resultPlainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.resultPlainTextEdit.setObjectName("resultPlainTextEdit")
        self.resultVerticalLayout.addWidget(self.resultPlainTextEdit)
        self.horizontalLayout_2.addLayout(self.resultVerticalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.keyVerticalLayout = QtWidgets.QVBoxLayout()
        self.keyVerticalLayout.setObjectName("keyVerticalLayout")
        self.keyLabel = QtWidgets.QLabel(self.centralwidget)
        self.keyLabel.setObjectName("keyLabel")
        self.keyVerticalLayout.addWidget(self.keyLabel)
        self.keyLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.keyLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.keyLineEdit.setObjectName("keyLineEdit")
        self.keyVerticalLayout.addWidget(self.keyLineEdit)
        self.verticalLayout.addLayout(self.keyVerticalLayout)
        self.buttonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.buttonsHorizontalLayout.setObjectName("buttonsHorizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsHorizontalLayout.addItem(spacerItem2)
        self.startPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startPushButton.setObjectName("startPushButton")
        self.buttonsHorizontalLayout.addWidget(self.startPushButton)
        self.savePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.savePushButton.setObjectName("savePushButton")
        self.buttonsHorizontalLayout.addWidget(self.savePushButton)
        self.exitPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitPushButton.setObjectName("exitPushButton")
        self.buttonsHorizontalLayout.addWidget(self.exitPushButton)
        self.verticalLayout.addLayout(self.buttonsHorizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.encryptionModeGroupBox.setTitle(_translate("MainWindow", "Encryption mode"))
        self.encryptionModeRadioButton.setText(_translate("MainWindow", "Encrypt"))
        self.decryptionModeRadioButton.setText(_translate("MainWindow", "Decrypt"))
        self.fromGroupBox.setTitle(_translate("MainWindow", "From"))
        self.fromPlainTextRadioButton.setText(_translate("MainWindow", "Plain text"))
        self.fromFileRadioButton.setText(_translate("MainWindow", "File"))
        self.toGroupBox.setTitle(_translate("MainWindow", "To"))
        self.toPlainTextRadioButton.setText(_translate("MainWindow", "Plain text"))
        self.toFileRadioButton.setText(_translate("MainWindow", "File"))
        self.encryptionMethodLabel.setText(_translate("MainWindow", "Encryption method:"))
        self.pathToSourceGroupBox.setTitle(_translate("MainWindow", "Path to source file"))
        self.viewSourcePushButton.setText(_translate("MainWindow", "View"))
        self.pathToDestFileGroupBox.setTitle(_translate("MainWindow", "Path to destination file"))
        self.viewDestPushButton.setText(_translate("MainWindow", "View"))
        self.sourceLabel.setText(_translate("MainWindow", "Source:"))
        self.resultLabel.setText(_translate("MainWindow", "Result:"))
        self.keyLabel.setText(_translate("MainWindow", "Key:"))
        self.startPushButton.setText(_translate("MainWindow", "Start"))
        self.savePushButton.setText(_translate("MainWindow", "Save"))
        self.exitPushButton.setText(_translate("MainWindow", "Exit"))
        self.action.setText(_translate("MainWindow", "Сохранить как..."))
        self.action_2.setText(_translate("MainWindow", "Выход"))
